package com.example.diary.Sql.Repository;

import java.util.List;

import org.springframework.dao.DataAccessException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

import com.example.diary.Models.DiaryModel;
import com.example.diary.Sql.DiaryRowMapper;

@Repository
public class DemoRepository extends BaseRepository {

    protected DemoRepository(JdbcTemplate jdbcTemplate) {
        super(jdbcTemplate);
        if (BaseRepository.databaseAccess == "org.hsqldb.jdbcDriver")
            createTable();
    }

    // テーブルの作成
    public void createTable() {
        System.out.println("DemoRepository.createTableを通過");
        String sql = "CREATE TABLE MyDiary (" +
                "Id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "tagType VARCHAR(10) NOT NULL, " +
                "mainString VARCHAR(200) NOT NULL, " +
                "dateTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, " +
                "emphasis INTEGER" +
                ")";
        jdbcTemplate.execute(sql);
        System.out.println("createTable完了");
    }

    // 直近30日を取り出すセレクト文
    public List<DiaryModel> select30days() throws DataAccessException, IllegalArgumentException {
        DiaryRowMapper rowMapper = new DiaryRowMapper();
        System.out.println("DiarySelectRepository.select30daysを通過");
        List<DiaryModel> list = jdbcTemplate.query(
                "SELECT * FROM MyDiary WHERE dateTime >= CURRENT_TIMESTAMP - 30 DAY ORDER BY emphasis DESC, Id DESC",
                rowMapper);
        System.out.println("select30days完了");
        return list;
    }

    // 以下のクエリはMySQLと同じ

}
